name: frontend-ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feat/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Node project
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "has_node=true" >> $GITHUB_OUTPUT
          else
            echo "has_node=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip (no frontend project yet)
        if: steps.detect.outputs.has_node == 'false'
        run: echo "No package.json yet — skipping build."

      - name: Set up Node
        if: steps.detect.outputs.has_node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20   # (no cache until we have a lockfile)

      - name: Install deps
        if: steps.detect.outputs.has_node == 'true'
        run: npm ci || npm install

      - name: Test (non-blocking)
        if: steps.detect.outputs.has_node == 'true'
        run: npm test -- --ci --watch=false || true

      - name: Build
        if: steps.detect.outputs.has_node == 'true'
        run: npm run build || echo "No build script yet"